apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-kieserver-deployment
spec:
  selector:
    matchLabels:
      run: drools-kieserver
  replicas: 1
  template:
    metadata:
      labels:
        run: drools-kieserver
    spec:
      containers:
      - name: drools-kieserver
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
