apiVersion: v1
kind: Service
metadata:
  name: drools-kieserver-service
  labels:
    run: drools-kieserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: drools-kieserver
